FROM harbor.crdigital.com.cn/library/nginx:1.22.0
LABEL maintainer="Ma Haoqiang"

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY dist /usr/share/nginx/html

WORKDIR /usr/share/nginx/html